### ISSUE TITLE
Cannot install the plugin

### ISSUE THREAD

**Issue by guaranadev** [duc12597/insomnia-plugin-response-regex#1]
When I try to install the plugin on Insomnia 7.1.1 on Windows, the following error is displayed:

```
insomnia-plugin-response-regex install error: Command failed: "C:\Users\MY_USERNAME\AppData\Local\insomnia\app-7.1.1\Insomnia.exe" --no-deprecation "C:\Users\MY_USERNAME\AppData\Local\insomnia\app-7.1.1\resources\bin\yarn-standalone.js" add insomnia-plugin-response-regex --modules-folder "C:\Users\MY_USERNAME\AppData\Local\Temp\insomnia_7.1.1\insomnia-plugin-response-regex-1587737777810" --cwd "C:\Users\MY_USERNAME\AppData\Local\Temp\insomnia_7.1.1\insomnia-plugin-response-regex-1587737777810" --no-lockfile --production --no-progress
error C:\Users\MY_USERNAME\AppData\Local\Temp\insomnia_7.1.1\insomnia-plugin-response-regex-1587737777810\jsonpath: Command failed.
Exit code: 1
Command: node lib/aesprim.js > generated/aesprim-browser.js
Arguments: 
Directory: C:\Users\MY_USERNAME\AppData\Local\Temp\insomnia_7.1.1\insomnia-plugin-response-regex-1587737777810\jsonpath
Output:
internal/modules/cjs/loader.js:604
    throw err;
    ^

Error: Cannot find module 'esprima'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Object.<anonymous> (C:\Users\MY_USERNAME\AppData\Local\Temp\insomnia_7.1.1\insomnia-plugin-response-regex-1587737777810\jsonpath\lib\aesprim.js:4:20)
    at Object.<anonymous> (C:\Users\MY_USERNAME\AppData\Local\Temp\insomnia_7.1.1\insomnia-plugin-response-regex-1587737777810\jsonpath\lib\aesprim.js:20:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:753:10)
```

**Comment by guaranadev** [comment]
I was able to install the plugin by cloning this repo to Insomnia's plugin directory and then running `npm install`. Insomnia then picked up the plugin automatically

**Comment by duc12597** [comment]
Will look into a fix for this. It would be much appreciated if someone create a pull request for a solution. For the time being, please clone the repo to Insomnia's plugin directory and manually run `npm install` like @guaranadev did.

**Comment by Geobert** [comment]
Hi, 

I've cloned the repo and inside I've run:
```
npm install

> jsonpath@1.0.2 postinstall C:\Users\geobe\work\insomnia-plugin-response-regex\node_modules\jsonpath
> node lib/aesprim.js > generated/aesprim-browser.js

npm WARN insomnia-plugin-response-regex@1.0.0 No license field.

added 25 packages from 71 contributors and audited 25 packages in 1.44s
found 0 vulnerabilities
```

But Insomnia doesn't seem to load it, what did I miss?

**Comment by Geobert** [comment]
Ok, I've copied the repo in the plugins directory and it was loaded.

How do I express to return only one of the match group?
